[package]
name = "flodoc_gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "flo"
path = "src/main.rs"

[dependencies]
pest = "2.7.10"
pest_derive = "2.7.10"
clap = { version = "4.5.7", features = ["derive"] }
serde_json = "1.0.117"
